### ISSUE TITLE
测试指定域名或ip的URL

### ISSUE THREAD

**Issue by xxcdd** [amcai/myscan#10]
如题：如何测试指定域名或ip的URL
PS：我用docker在本地成功部署了该项目，Dockerfile在这：`https://github.com/xxcdd/myscan`，是否可以加入主仓库呢

**Comment by amcai** [comment]
可以通过--host参数，如测试weibo,可使用 --host weibo.com  weibo.cn ,或者 --host weibo 都可以，使用的是包含关系。感谢提供dockerfile，后续加入主仓库。

**Comment by xxcdd** [comment]
burpsuite入库Redis这个过程中可以指定域名或ip的URL吗

**Comment by amcai** [comment]
可以通过关闭proxy mode为close，然后右键指定数据包"send to myscan"去指定数据包发送到redis。
